### ISSUE TITLE
简单、方便、实用，唯一不足，缺少批量删除操作，根据前缀删除

### ISSUE THREAD

**Issue by eric7166** [doobo/union-cache#1]
看到最好的缓存库了，简单、方便、实用，
唯一不足，缺少批量删除操作，根据前缀删除，
如果能增加这个功能，会更好的

**Comment by doobo** [comment]
欢迎提交更新，可以在del注解上加个字段，可选择批量删除，如果是批量删除类型，走批量删除的服务接口

**Comment by doobo** [comment]
本地缓存添加了简单基于*结尾的批量删除，其它自定义缓存实现batchClear方法即可
