### ISSUE TITLE
新的版本总是报错

### ISSUE THREAD

**Issue by eric7166** [doobo/union-cache#2]
新的版本，缓存有问题，总是报错，是改什么机制了吗？
java.lang.ClassCastException: java.lang.String cannot be cast to

1.2.1正常  1.2.2都是报错

**Comment by eric7166** [comment]
存储的对象  全变成了字符串  并且是加密的了  好像

**Comment by doobo** [comment]
是不是1.2.1切换的1.2.2,如果同时存在，1.2.2要启用下压缩，以前1.2.1时默认全部压缩的。
` /**
     * 是否开启压缩
     */
    boolean enableCompress();
`
