### ISSUE TITLE
我发下了一个bug，@DCache 加在返回类型为空的方法上，是无效的

### ISSUE THREAD

**Issue by eric7166** [doobo/union-cache#5]
我发下了一个bug，反馈下，希望修复一下
@DCache 加在返回类型为空的方法上，是无效的，不会调用删除事件
例如:  void saveConfig(UserConfig config)

**Comment by doobo** [comment]
修复到1.3上，去掉了一些不必要的代码结构，改了下服务实现方式，支持多个缓存写入

**Comment by eric7166** [comment]
太棒了  感谢
太好用了
