### ISSUE TITLE
最新版本1.3无法搜索到

### ISSUE THREAD

**Issue by eric7166** [doobo/union-cache#6]
最新版本1.3无法再阿里云镜像搜索到
https://maven.aliyun.com/nexus/content/groups/public

本地加了很多镜像可以，但是远程发布 构建里只有public镜像
之前的包可以搜到

**Comment by doobo** [comment]
自2022.12.12起，受 Maven 中央仓库网络限制，阿里云云效 Maven 中央代理仓库可能会出现部分新增依赖查找不到的情况，但不影响已有依赖，请知悉
